### Login
POST http://127.0.0.1:8000/login
Content-Type: application/json

{
    "usuario": "admin",
    "contrasena": "admin123"
}

### Login con correo
POST http://127.0.0.1:8000/login
Content-Type: application/json

{
    "usuario": "admin@logitrans.com",
    "contrasena": "admin123"
}

### Logout
POST http://127.0.0.1:8000/logout
Authorization: a1045aa415825b543bba0ff84364e23f2ebc41e0c7f5d3f982305e9dcee14849

### Validar token
GET http://127.0.0.1:8000/validarToken
Authorization: e6223465c90597c649798b40a033400a512945300b72d115485bfe68ad0e69fb