### Listar vehiculos
GET http://127.0.0.1:8002/vehiculos

### Buscar por placa
GET http://127.0.0.1:8002/vehiculos/placa/ABC123

### Buscar por estado
GET http://127.0.0.1:8002/vehiculos/estado/disponible

### Buscar por tipo
GET http://127.0.0.1:8002/vehiculos/tipo/Camion

### Crear vehiculo
POST http://127.0.0.1:8002/vehiculos
Content-Type: application/json

{
    "placa": "DEF456",
    "tipo_vehiculo": "Camioneta",
    "capacidad_carga": 1000,
    "modelo": "2023",
    "marca": "Toyota"
}

### Cambiar estado
PATCH http://127.0.0.1:8002/vehiculos/1/estado
Content-Type: application/json

{
    "estado": "mantenimiento"
}